In [1]:
import numpy as np
import torch
from torchvision import models, transforms
import cv2

In [2]:
def preprocessImage(imagePath):
    image = cv2.imread(imagePath) # loads pixel values
    image = cv2.resize(image, (256, 256)) # resizes to be square shape
    image = image / 255.0 # normalizes the light values, so the pixel values range from 0 to 1.
    return image

In [3]:
array = np.array(preprocessImage("images/butterfly/e030b20a20e90021d85a5854ee454296eb70e3c818b413449df6c87ca3ed_640.jpg"))
print(array.shape)
print(array)

(256, 256, 3)
[[[0.51372549 0.8627451  0.82745098]
  [0.5372549  0.87843137 0.85882353]
  [0.56078431 0.89019608 0.87843137]
  ...
  [0.18039216 0.76078431 0.68235294]
  [0.17647059 0.76078431 0.68235294]
  [0.17647059 0.76078431 0.68235294]]

 [[0.50980392 0.85882353 0.82352941]
  [0.54117647 0.87843137 0.85882353]
  [0.56078431 0.89019608 0.87843137]
  ...
  [0.18431373 0.76078431 0.68235294]
  [0.17647059 0.76078431 0.68235294]
  [0.17647059 0.76078431 0.68235294]]

 [[0.50980392 0.85882353 0.82352941]
  [0.54117647 0.87843137 0.85882353]
  [0.56078431 0.89019608 0.87843137]
  ...
  [0.18431373 0.76078431 0.68235294]
  [0.17647059 0.76078431 0.68235294]
  [0.17647059 0.76078431 0.68235294]]

 ...

 [[0.18823529 0.85098039 0.78039216]
  [0.17254902 0.84313725 0.78039216]
  [0.15686275 0.84705882 0.78039216]
  ...
  [0.38431373 0.81960784 0.74117647]
  [0.4        0.82352941 0.74901961]
  [0.40784314 0.82745098 0.75294118]]

 [[0.25882353 0.85490196 0.79607843]
  [0.23137255 0.8549019

In [4]:
# def initialize_parameters():
    # weights = np.random.rand(1,n) # creates a 1 x n array of values where n is the number of features in the input.